# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42f5f9bc39737d9d19053952ebc748750bf4e31dfff85b1e2bd3092d8999c71edee992cdecb3edf17709b7aee0bd99413cb5787b68dba29cad6161b3c95fa2b5

test:
  secret_key_base: 001dcfc19b40d92c5c1a86bb66e877024341f6d4ae772b8a20cdbe66d843c4c051b8c277605577203fd06c9db224902e1d607fc39117a01fb414b6139b2a8297

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
